# Generated by Django 4.1.7 on 2023-04-18 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_account'),
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='cartfilm',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.profil', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='cartfilm',
            name='tag',
            field=models.ManyToManyField(null=True, to='appMy.tag', verbose_name='Tag'),
        ),
    ]
