# Generated by Django 4.1.7 on 2023-04-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_tag_alter_cartfilm_profil_cartfilm_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartfilm',
            name='profil',
        ),
    ]
