# Generated by Django 4.1.7 on 2023-04-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_remove_cartfilm_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartfilm',
            name='tag',
            field=models.ManyToManyField(blank=True, to='appMy.tag', verbose_name='Tag'),
        ),
    ]
