# Generated by Django 4.1.7 on 2023-04-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_remove_cartfilm_profil'),
        ('appUser', '0004_profil_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='films',
            field=models.ManyToManyField(blank=True, to='appMy.cartfilm', verbose_name='fimleri'),
        ),
    ]
